# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: q32b-1p1d-cloud-provider
spec:
  services:
    PrefillWorker:
      extraPodSpec:
        mainContainer:
          env:
            - &nebiusTransfer
              name: KV_TRANSFER_CONFIG
              value: '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
    DecodeWorker:
      extraPodSpec:
        mainContainer:
          env:
            - *nebiusTransfer
            - name: UCX_RNDV_THRESH
              value: "8192"
