# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: qwen3-235b-a22b-disagg
spec:
  services:
    PrefillWorker:
      resources:
        limits:
          gpu: "2"
          custom:
            vpc.amazonaws.com/efa: "8"
        requests:
          gpu: "2"
          custom:
            vpc.amazonaws.com/efa: "8"
            ephemeral-storage: 2Gi
    DecodeWorker:
      resources:
        limits:
          gpu: "4"
          custom:
            vpc.amazonaws.com/efa: "16"
        requests:
          gpu: "4"
          custom:
            vpc.amazonaws.com/efa: "16"
            ephemeral-storage: 2Gi
