# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: q32b-1p1d-cloud-provider
spec:
  services:
    Frontend:
      extraPodSpec:
        imagePullSecrets:
          - name: nvcr-pull-secret
    PrefillWorker:
      extraPodSpec:
        imagePullSecrets:
          - name: nvcr-pull-secret
        mainContainer:
          env: &vllmEnvironment
            - name: KV_TRANSFER_CONFIG
              value: '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
          volumeMounts: &modelCacheVolumeMounts
            - name: model-cache
              mountPath: /model-cache
        volumes: &modelCacheVolumes
          - name: model-cache
            persistentVolumeClaim:
              claimName: model-cache
    DecodeWorker:
      extraPodSpec:
        imagePullSecrets:
          - name: nvcr-pull-secret
        mainContainer:
          env: *vllmEnvironment
          volumeMounts: *modelCacheVolumeMounts
        volumes: *modelCacheVolumes
