# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: qwen3-235b-a22b-disagg
spec:
  services:
    PrefillWorker:
      resources:
        limits:
          gpu: "2"
        requests:
          gpu: "2"
          custom:
            ephemeral-storage: 2Gi
      extraPodSpec:
        mainContainer:
          volumeMounts:
            - name: prefill-config
              mountPath: /engine_configs
            - name: model-cache
              mountPath: /mnt/model-cache
        volumes:
          - name: prefill-config
            configMap:
              name: prefill-config
          - &modelCacheVolume
            name: model-cache
            persistentVolumeClaim:
              claimName: model-cache
    DecodeWorker:
      resources:
        limits:
          gpu: "4"
        requests:
          gpu: "4"
          custom:
            ephemeral-storage: 2Gi
      extraPodSpec:
        mainContainer:
          volumeMounts:
            - name: decode-config
              mountPath: /engine_configs
            - name: model-cache
              mountPath: /mnt/model-cache
        volumes:
          - name: decode-config
            configMap:
              name: decode-config
          - *modelCacheVolume
