// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v3.21.12
// source: pagebroker.proto

package pagebroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreRequest_Mode int32

const (
	RestoreRequest_MODE_UNSPECIFIED RestoreRequest_Mode = 0
	RestoreRequest_MODE_DIRECT      RestoreRequest_Mode = 1
	RestoreRequest_MODE_STAGED      RestoreRequest_Mode = 2
)

// Enum value maps for RestoreRequest_Mode.
var (
	RestoreRequest_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_DIRECT",
		2: "MODE_STAGED",
	}
	RestoreRequest_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_DIRECT":      1,
		"MODE_STAGED":      2,
	}
)

func (x RestoreRequest_Mode) Enum() *RestoreRequest_Mode {
	p := new(RestoreRequest_Mode)
	*p = x
	return p
}

func (x RestoreRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestoreRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_pagebroker_proto_enumTypes[0].Descriptor()
}

func (RestoreRequest_Mode) Type() protoreflect.EnumType {
	return &file_pagebroker_proto_enumTypes[0]
}

func (x RestoreRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RestoreRequest_Mode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RestoreRequest_Mode(num)
	return nil
}

// Deprecated: Use RestoreRequest_Mode.Descriptor instead.
func (RestoreRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{0, 0}
}

type ErrorResponse_Code int32

const (
	ErrorResponse_CODE_UNSPECIFIED        ErrorResponse_Code = 0
	ErrorResponse_CODE_INVALID_REQUEST    ErrorResponse_Code = 1
	ErrorResponse_CODE_NOT_FOUND          ErrorResponse_Code = 2
	ErrorResponse_CODE_CONFLICT           ErrorResponse_Code = 3
	ErrorResponse_CODE_RESOURCE_EXHAUSTED ErrorResponse_Code = 4
	ErrorResponse_CODE_IO                 ErrorResponse_Code = 5
	ErrorResponse_CODE_INTERNAL           ErrorResponse_Code = 6
)

// Enum value maps for ErrorResponse_Code.
var (
	ErrorResponse_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_INVALID_REQUEST",
		2: "CODE_NOT_FOUND",
		3: "CODE_CONFLICT",
		4: "CODE_RESOURCE_EXHAUSTED",
		5: "CODE_IO",
		6: "CODE_INTERNAL",
	}
	ErrorResponse_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":        0,
		"CODE_INVALID_REQUEST":    1,
		"CODE_NOT_FOUND":          2,
		"CODE_CONFLICT":           3,
		"CODE_RESOURCE_EXHAUSTED": 4,
		"CODE_IO":                 5,
		"CODE_INTERNAL":           6,
	}
)

func (x ErrorResponse_Code) Enum() *ErrorResponse_Code {
	p := new(ErrorResponse_Code)
	*p = x
	return p
}

func (x ErrorResponse_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorResponse_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_pagebroker_proto_enumTypes[1].Descriptor()
}

func (ErrorResponse_Code) Type() protoreflect.EnumType {
	return &file_pagebroker_proto_enumTypes[1]
}

func (x ErrorResponse_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ErrorResponse_Code) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ErrorResponse_Code(num)
	return nil
}

// Deprecated: Use ErrorResponse_Code.Descriptor instead.
func (ErrorResponse_Code) EnumDescriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{9, 0}
}

type RestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The existing checkpoint directory to restore.
	SourcePath *string `protobuf:"bytes,1,opt,name=source_path,json=sourcePath" json:"source_path,omitempty"`
	// Required. The PageBroker restore mode.
	Mode *RestoreRequest_Mode `protobuf:"varint,2,opt,name=mode,enum=snapshot.pagebroker.RestoreRequest_Mode" json:"mode,omitempty"`
	// Required for staged restore. Generated by Snapshot.
	TransactionId *string `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pagebroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreRequest) GetSourcePath() string {
	if x != nil && x.SourcePath != nil {
		return *x.SourcePath
	}
	return ""
}

func (x *RestoreRequest) GetMode() RestoreRequest_Mode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return RestoreRequest_MODE_UNSPECIFIED
}

func (x *RestoreRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type PrepareCheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The checkpoint directory to publish on commit.
	DestinationPath *string `protobuf:"bytes,1,opt,name=destination_path,json=destinationPath" json:"destination_path,omitempty"`
	// Required. Generated by Snapshot.
	TransactionId *string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareCheckpointRequest) Reset() {
	*x = PrepareCheckpointRequest{}
	mi := &file_pagebroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareCheckpointRequest) ProtoMessage() {}

func (x *PrepareCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareCheckpointRequest.ProtoReflect.Descriptor instead.
func (*PrepareCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareCheckpointRequest) GetDestinationPath() string {
	if x != nil && x.DestinationPath != nil {
		return *x.DestinationPath
	}
	return ""
}

func (x *PrepareCheckpointRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type CommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. A transaction generated by Snapshot.
	TransactionId *string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_pagebroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type AbortRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. A transaction generated by Snapshot.
	TransactionId *string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_pagebroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{3}
}

func (x *AbortRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*Request_Restore
	//	*Request_PrepareCheckpoint
	//	*Request_Commit
	//	*Request_Abort
	Command       isRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pagebroker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetCommand() isRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Request) GetRestore() *RestoreRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *Request) GetPrepareCheckpoint() *PrepareCheckpointRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_PrepareCheckpoint); ok {
			return x.PrepareCheckpoint
		}
	}
	return nil
}

func (x *Request) GetCommit() *CommitRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Request) GetAbort() *AbortRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

type isRequest_Command interface {
	isRequest_Command()
}

type Request_Restore struct {
	Restore *RestoreRequest `protobuf:"bytes,1,opt,name=restore,oneof"`
}

type Request_PrepareCheckpoint struct {
	PrepareCheckpoint *PrepareCheckpointRequest `protobuf:"bytes,2,opt,name=prepare_checkpoint,json=prepareCheckpoint,oneof"`
}

type Request_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,3,opt,name=commit,oneof"`
}

type Request_Abort struct {
	Abort *AbortRequest `protobuf:"bytes,4,opt,name=abort,oneof"`
}

func (*Request_Restore) isRequest_Command() {}

func (*Request_PrepareCheckpoint) isRequest_Command() {}

func (*Request_Commit) isRequest_Command() {}

func (*Request_Abort) isRequest_Command() {}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryPath *string                `protobuf:"bytes,1,opt,name=directory_path,json=directoryPath" json:"directory_path,omitempty"`
	TransactionId *string                `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_pagebroker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreResponse) GetDirectoryPath() string {
	if x != nil && x.DirectoryPath != nil {
		return *x.DirectoryPath
	}
	return ""
}

func (x *RestoreResponse) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type PrepareCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryPath *string                `protobuf:"bytes,1,opt,name=directory_path,json=directoryPath" json:"directory_path,omitempty"`
	TransactionId *string                `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareCheckpointResponse) Reset() {
	*x = PrepareCheckpointResponse{}
	mi := &file_pagebroker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareCheckpointResponse) ProtoMessage() {}

func (x *PrepareCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareCheckpointResponse.ProtoReflect.Descriptor instead.
func (*PrepareCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareCheckpointResponse) GetDirectoryPath() string {
	if x != nil && x.DirectoryPath != nil {
		return *x.DirectoryPath
	}
	return ""
}

func (x *PrepareCheckpointResponse) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryPath *string                `protobuf:"bytes,1,opt,name=directory_path,json=directoryPath" json:"directory_path,omitempty"`
	TransactionId *string                `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_pagebroker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{7}
}

func (x *CommitResponse) GetDirectoryPath() string {
	if x != nil && x.DirectoryPath != nil {
		return *x.DirectoryPath
	}
	return ""
}

func (x *CommitResponse) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId *string                `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_pagebroker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{8}
}

func (x *AbortResponse) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *ErrorResponse_Code    `protobuf:"varint,1,opt,name=code,enum=snapshot.pagebroker.ErrorResponse_Code" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_pagebroker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorResponse) GetCode() ErrorResponse_Code {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ErrorResponse_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*Response_Restore
	//	*Response_PrepareCheckpoint
	//	*Response_Commit
	//	*Response_Abort
	//	*Response_Error
	Outcome       isResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pagebroker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetOutcome() isResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *Response) GetRestore() *RestoreResponse {
	if x != nil {
		if x, ok := x.Outcome.(*Response_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *Response) GetPrepareCheckpoint() *PrepareCheckpointResponse {
	if x != nil {
		if x, ok := x.Outcome.(*Response_PrepareCheckpoint); ok {
			return x.PrepareCheckpoint
		}
	}
	return nil
}

func (x *Response) GetCommit() *CommitResponse {
	if x != nil {
		if x, ok := x.Outcome.(*Response_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Response) GetAbort() *AbortResponse {
	if x != nil {
		if x, ok := x.Outcome.(*Response_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

func (x *Response) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Outcome.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isResponse_Outcome interface {
	isResponse_Outcome()
}

type Response_Restore struct {
	Restore *RestoreResponse `protobuf:"bytes,1,opt,name=restore,oneof"`
}

type Response_PrepareCheckpoint struct {
	PrepareCheckpoint *PrepareCheckpointResponse `protobuf:"bytes,2,opt,name=prepare_checkpoint,json=prepareCheckpoint,oneof"`
}

type Response_Commit struct {
	Commit *CommitResponse `protobuf:"bytes,3,opt,name=commit,oneof"`
}

type Response_Abort struct {
	Abort *AbortResponse `protobuf:"bytes,4,opt,name=abort,oneof"`
}

type Response_Error struct {
	Error *ErrorResponse `protobuf:"bytes,5,opt,name=error,oneof"`
}

func (*Response_Restore) isResponse_Outcome() {}

func (*Response_PrepareCheckpoint) isResponse_Outcome() {}

func (*Response_Commit) isResponse_Outcome() {}

func (*Response_Abort) isResponse_Outcome() {}

func (*Response_Error) isResponse_Outcome() {}

var File_pagebroker_proto protoreflect.FileDescriptor

const file_pagebroker_proto_rawDesc = "" +
	"\n" +
	"\x10pagebroker.proto\x12\x13snapshot.pagebroker\"\xd6\x01\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12<\n" +
	"\x04mode\x18\x02 \x01(\x0e2(.snapshot.pagebroker.RestoreRequest.ModeR\x04mode\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\">\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMODE_DIRECT\x10\x01\x12\x0f\n" +
	"\vMODE_STAGED\x10\x02\"l\n" +
	"\x18PrepareCheckpointRequest\x12)\n" +
	"\x10destination_path\x18\x01 \x01(\tR\x0fdestinationPath\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"6\n" +
	"\rCommitRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"5\n" +
	"\fAbortRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\xae\x02\n" +
	"\aRequest\x12?\n" +
	"\arestore\x18\x01 \x01(\v2#.snapshot.pagebroker.RestoreRequestH\x00R\arestore\x12^\n" +
	"\x12prepare_checkpoint\x18\x02 \x01(\v2-.snapshot.pagebroker.PrepareCheckpointRequestH\x00R\x11prepareCheckpoint\x12<\n" +
	"\x06commit\x18\x03 \x01(\v2\".snapshot.pagebroker.CommitRequestH\x00R\x06commit\x129\n" +
	"\x05abort\x18\x04 \x01(\v2!.snapshot.pagebroker.AbortRequestH\x00R\x05abortB\t\n" +
	"\acommand\"_\n" +
	"\x0fRestoreResponse\x12%\n" +
	"\x0edirectory_path\x18\x01 \x01(\tR\rdirectoryPath\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"i\n" +
	"\x19PrepareCheckpointResponse\x12%\n" +
	"\x0edirectory_path\x18\x01 \x01(\tR\rdirectoryPath\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"^\n" +
	"\x0eCommitResponse\x12%\n" +
	"\x0edirectory_path\x18\x01 \x01(\tR\rdirectoryPath\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"6\n" +
	"\rAbortResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x83\x02\n" +
	"\rErrorResponse\x12;\n" +
	"\x04code\x18\x01 \x01(\x0e2'.snapshot.pagebroker.ErrorResponse.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9a\x01\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CODE_INVALID_REQUEST\x10\x01\x12\x12\n" +
	"\x0eCODE_NOT_FOUND\x10\x02\x12\x11\n" +
	"\rCODE_CONFLICT\x10\x03\x12\x1b\n" +
	"\x17CODE_RESOURCE_EXHAUSTED\x10\x04\x12\v\n" +
	"\aCODE_IO\x10\x05\x12\x11\n" +
	"\rCODE_INTERNAL\x10\x06\"\xef\x02\n" +
	"\bResponse\x12@\n" +
	"\arestore\x18\x01 \x01(\v2$.snapshot.pagebroker.RestoreResponseH\x00R\arestore\x12_\n" +
	"\x12prepare_checkpoint\x18\x02 \x01(\v2..snapshot.pagebroker.PrepareCheckpointResponseH\x00R\x11prepareCheckpoint\x12=\n" +
	"\x06commit\x18\x03 \x01(\v2#.snapshot.pagebroker.CommitResponseH\x00R\x06commit\x12:\n" +
	"\x05abort\x18\x04 \x01(\v2\".snapshot.pagebroker.AbortResponseH\x00R\x05abort\x12:\n" +
	"\x05error\x18\x05 \x01(\v2\".snapshot.pagebroker.ErrorResponseH\x00R\x05errorB\t\n" +
	"\aoutcomeBAZ?github.com/ai-dynamo/dynamo/deploy/snapshot/internal/pagebroker"

var (
	file_pagebroker_proto_rawDescOnce sync.Once
	file_pagebroker_proto_rawDescData []byte
)

func file_pagebroker_proto_rawDescGZIP() []byte {
	file_pagebroker_proto_rawDescOnce.Do(func() {
		file_pagebroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pagebroker_proto_rawDesc), len(file_pagebroker_proto_rawDesc)))
	})
	return file_pagebroker_proto_rawDescData
}

var file_pagebroker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pagebroker_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pagebroker_proto_goTypes = []any{
	(RestoreRequest_Mode)(0),          // 0: snapshot.pagebroker.RestoreRequest.Mode
	(ErrorResponse_Code)(0),           // 1: snapshot.pagebroker.ErrorResponse.Code
	(*RestoreRequest)(nil),            // 2: snapshot.pagebroker.RestoreRequest
	(*PrepareCheckpointRequest)(nil),  // 3: snapshot.pagebroker.PrepareCheckpointRequest
	(*CommitRequest)(nil),             // 4: snapshot.pagebroker.CommitRequest
	(*AbortRequest)(nil),              // 5: snapshot.pagebroker.AbortRequest
	(*Request)(nil),                   // 6: snapshot.pagebroker.Request
	(*RestoreResponse)(nil),           // 7: snapshot.pagebroker.RestoreResponse
	(*PrepareCheckpointResponse)(nil), // 8: snapshot.pagebroker.PrepareCheckpointResponse
	(*CommitResponse)(nil),            // 9: snapshot.pagebroker.CommitResponse
	(*AbortResponse)(nil),             // 10: snapshot.pagebroker.AbortResponse
	(*ErrorResponse)(nil),             // 11: snapshot.pagebroker.ErrorResponse
	(*Response)(nil),                  // 12: snapshot.pagebroker.Response
}
var file_pagebroker_proto_depIdxs = []int32{
	0,  // 0: snapshot.pagebroker.RestoreRequest.mode:type_name -> snapshot.pagebroker.RestoreRequest.Mode
	2,  // 1: snapshot.pagebroker.Request.restore:type_name -> snapshot.pagebroker.RestoreRequest
	3,  // 2: snapshot.pagebroker.Request.prepare_checkpoint:type_name -> snapshot.pagebroker.PrepareCheckpointRequest
	4,  // 3: snapshot.pagebroker.Request.commit:type_name -> snapshot.pagebroker.CommitRequest
	5,  // 4: snapshot.pagebroker.Request.abort:type_name -> snapshot.pagebroker.AbortRequest
	1,  // 5: snapshot.pagebroker.ErrorResponse.code:type_name -> snapshot.pagebroker.ErrorResponse.Code
	7,  // 6: snapshot.pagebroker.Response.restore:type_name -> snapshot.pagebroker.RestoreResponse
	8,  // 7: snapshot.pagebroker.Response.prepare_checkpoint:type_name -> snapshot.pagebroker.PrepareCheckpointResponse
	9,  // 8: snapshot.pagebroker.Response.commit:type_name -> snapshot.pagebroker.CommitResponse
	10, // 9: snapshot.pagebroker.Response.abort:type_name -> snapshot.pagebroker.AbortResponse
	11, // 10: snapshot.pagebroker.Response.error:type_name -> snapshot.pagebroker.ErrorResponse
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pagebroker_proto_init() }
func file_pagebroker_proto_init() {
	if File_pagebroker_proto != nil {
		return
	}
	file_pagebroker_proto_msgTypes[4].OneofWrappers = []any{
		(*Request_Restore)(nil),
		(*Request_PrepareCheckpoint)(nil),
		(*Request_Commit)(nil),
		(*Request_Abort)(nil),
	}
	file_pagebroker_proto_msgTypes[10].OneofWrappers = []any{
		(*Response_Restore)(nil),
		(*Response_PrepareCheckpoint)(nil),
		(*Response_Commit)(nil),
		(*Response_Abort)(nil),
		(*Response_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pagebroker_proto_rawDesc), len(file_pagebroker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pagebroker_proto_goTypes,
		DependencyIndexes: file_pagebroker_proto_depIdxs,
		EnumInfos:         file_pagebroker_proto_enumTypes,
		MessageInfos:      file_pagebroker_proto_msgTypes,
	}.Build()
	File_pagebroker_proto = out.File
	file_pagebroker_proto_goTypes = nil
	file_pagebroker_proto_depIdxs = nil
}
