// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v3.21.12
// source: pagebroker.proto

package pagebroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreRequest_Mode int32

const (
	RestoreRequest_MODE_UNSPECIFIED RestoreRequest_Mode = 0
	RestoreRequest_MODE_DIRECT      RestoreRequest_Mode = 1
	RestoreRequest_MODE_STAGED      RestoreRequest_Mode = 2
)

// Enum value maps for RestoreRequest_Mode.
var (
	RestoreRequest_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_DIRECT",
		2: "MODE_STAGED",
	}
	RestoreRequest_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_DIRECT":      1,
		"MODE_STAGED":      2,
	}
)

func (x RestoreRequest_Mode) Enum() *RestoreRequest_Mode {
	p := new(RestoreRequest_Mode)
	*p = x
	return p
}

func (x RestoreRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestoreRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_pagebroker_proto_enumTypes[0].Descriptor()
}

func (RestoreRequest_Mode) Type() protoreflect.EnumType {
	return &file_pagebroker_proto_enumTypes[0]
}

func (x RestoreRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RestoreRequest_Mode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RestoreRequest_Mode(num)
	return nil
}

// Deprecated: Use RestoreRequest_Mode.Descriptor instead.
func (RestoreRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{0, 0}
}

type RestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The existing checkpoint directory to restore.
	SourcePath *string `protobuf:"bytes,1,opt,name=source_path,json=sourcePath" json:"source_path,omitempty"`
	// Required. The PageBroker restore mode.
	Mode          *RestoreRequest_Mode `protobuf:"varint,2,opt,name=mode,enum=snapshot.pagebroker.RestoreRequest_Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pagebroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreRequest) GetSourcePath() string {
	if x != nil && x.SourcePath != nil {
		return *x.SourcePath
	}
	return ""
}

func (x *RestoreRequest) GetMode() RestoreRequest_Mode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return RestoreRequest_MODE_UNSPECIFIED
}

type PrepareCheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The checkpoint directory to publish on commit.
	DestinationPath *string `protobuf:"bytes,1,opt,name=destination_path,json=destinationPath" json:"destination_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrepareCheckpointRequest) Reset() {
	*x = PrepareCheckpointRequest{}
	mi := &file_pagebroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareCheckpointRequest) ProtoMessage() {}

func (x *PrepareCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareCheckpointRequest.ProtoReflect.Descriptor instead.
func (*PrepareCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareCheckpointRequest) GetDestinationPath() string {
	if x != nil && x.DestinationPath != nil {
		return *x.DestinationPath
	}
	return ""
}

type CommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The transaction returned by PrepareCheckpointRequest.
	TransactionId *string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_pagebroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type AbortRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. A checkpoint or staged restore transaction.
	TransactionId *string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_pagebroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{3}
}

func (x *AbortRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*Request_Restore
	//	*Request_PrepareCheckpoint
	//	*Request_Commit
	//	*Request_Abort
	Command       isRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pagebroker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetCommand() isRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Request) GetRestore() *RestoreRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *Request) GetPrepareCheckpoint() *PrepareCheckpointRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_PrepareCheckpoint); ok {
			return x.PrepareCheckpoint
		}
	}
	return nil
}

func (x *Request) GetCommit() *CommitRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Request) GetAbort() *AbortRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

type isRequest_Command interface {
	isRequest_Command()
}

type Request_Restore struct {
	Restore *RestoreRequest `protobuf:"bytes,1,opt,name=restore,oneof"`
}

type Request_PrepareCheckpoint struct {
	PrepareCheckpoint *PrepareCheckpointRequest `protobuf:"bytes,2,opt,name=prepare_checkpoint,json=prepareCheckpoint,oneof"`
}

type Request_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,3,opt,name=commit,oneof"`
}

type Request_Abort struct {
	Abort *AbortRequest `protobuf:"bytes,4,opt,name=abort,oneof"`
}

func (*Request_Restore) isRequest_Command() {}

func (*Request_PrepareCheckpoint) isRequest_Command() {}

func (*Request_Commit) isRequest_Command() {}

func (*Request_Abort) isRequest_Command() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. False means error contains the failure reason.
	Ok            *bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	TransactionId *string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	DirectoryPath *string `protobuf:"bytes,3,opt,name=directory_path,json=directoryPath" json:"directory_path,omitempty"`
	Error         *string `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pagebroker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pagebroker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pagebroker_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetOk() bool {
	if x != nil && x.Ok != nil {
		return *x.Ok
	}
	return false
}

func (x *Response) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

func (x *Response) GetDirectoryPath() string {
	if x != nil && x.DirectoryPath != nil {
		return *x.DirectoryPath
	}
	return ""
}

func (x *Response) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_pagebroker_proto protoreflect.FileDescriptor

const file_pagebroker_proto_rawDesc = "" +
	"\n" +
	"\x10pagebroker.proto\x12\x13snapshot.pagebroker\"\xaf\x01\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12<\n" +
	"\x04mode\x18\x02 \x01(\x0e2(.snapshot.pagebroker.RestoreRequest.ModeR\x04mode\">\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMODE_DIRECT\x10\x01\x12\x0f\n" +
	"\vMODE_STAGED\x10\x02\"E\n" +
	"\x18PrepareCheckpointRequest\x12)\n" +
	"\x10destination_path\x18\x01 \x01(\tR\x0fdestinationPath\"6\n" +
	"\rCommitRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"5\n" +
	"\fAbortRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\xae\x02\n" +
	"\aRequest\x12?\n" +
	"\arestore\x18\x01 \x01(\v2#.snapshot.pagebroker.RestoreRequestH\x00R\arestore\x12^\n" +
	"\x12prepare_checkpoint\x18\x02 \x01(\v2-.snapshot.pagebroker.PrepareCheckpointRequestH\x00R\x11prepareCheckpoint\x12<\n" +
	"\x06commit\x18\x03 \x01(\v2\".snapshot.pagebroker.CommitRequestH\x00R\x06commit\x129\n" +
	"\x05abort\x18\x04 \x01(\v2!.snapshot.pagebroker.AbortRequestH\x00R\x05abortB\t\n" +
	"\acommand\"~\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12%\n" +
	"\x0edirectory_path\x18\x03 \x01(\tR\rdirectoryPath\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorBAZ?github.com/ai-dynamo/dynamo/deploy/snapshot/internal/pagebroker"

var (
	file_pagebroker_proto_rawDescOnce sync.Once
	file_pagebroker_proto_rawDescData []byte
)

func file_pagebroker_proto_rawDescGZIP() []byte {
	file_pagebroker_proto_rawDescOnce.Do(func() {
		file_pagebroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pagebroker_proto_rawDesc), len(file_pagebroker_proto_rawDesc)))
	})
	return file_pagebroker_proto_rawDescData
}

var file_pagebroker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pagebroker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pagebroker_proto_goTypes = []any{
	(RestoreRequest_Mode)(0),         // 0: snapshot.pagebroker.RestoreRequest.Mode
	(*RestoreRequest)(nil),           // 1: snapshot.pagebroker.RestoreRequest
	(*PrepareCheckpointRequest)(nil), // 2: snapshot.pagebroker.PrepareCheckpointRequest
	(*CommitRequest)(nil),            // 3: snapshot.pagebroker.CommitRequest
	(*AbortRequest)(nil),             // 4: snapshot.pagebroker.AbortRequest
	(*Request)(nil),                  // 5: snapshot.pagebroker.Request
	(*Response)(nil),                 // 6: snapshot.pagebroker.Response
}
var file_pagebroker_proto_depIdxs = []int32{
	0, // 0: snapshot.pagebroker.RestoreRequest.mode:type_name -> snapshot.pagebroker.RestoreRequest.Mode
	1, // 1: snapshot.pagebroker.Request.restore:type_name -> snapshot.pagebroker.RestoreRequest
	2, // 2: snapshot.pagebroker.Request.prepare_checkpoint:type_name -> snapshot.pagebroker.PrepareCheckpointRequest
	3, // 3: snapshot.pagebroker.Request.commit:type_name -> snapshot.pagebroker.CommitRequest
	4, // 4: snapshot.pagebroker.Request.abort:type_name -> snapshot.pagebroker.AbortRequest
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pagebroker_proto_init() }
func file_pagebroker_proto_init() {
	if File_pagebroker_proto != nil {
		return
	}
	file_pagebroker_proto_msgTypes[4].OneofWrappers = []any{
		(*Request_Restore)(nil),
		(*Request_PrepareCheckpoint)(nil),
		(*Request_Commit)(nil),
		(*Request_Abort)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pagebroker_proto_rawDesc), len(file_pagebroker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pagebroker_proto_goTypes,
		DependencyIndexes: file_pagebroker_proto_depIdxs,
		EnumInfos:         file_pagebroker_proto_enumTypes,
		MessageInfos:      file_pagebroker_proto_msgTypes,
	}.Build()
	File_pagebroker_proto = out.File
	file_pagebroker_proto_goTypes = nil
	file_pagebroker_proto_depIdxs = nil
}
